version: 2

sources:
  - name: ecommerce
    database: bigquery-public-data
    schema: thelook_ecommerce
    tables:
      - name: distribution_centers
      - name: events
      - name: inventory_items
      - name: order_items
      - name: orders
      - name: products
      - name: users